# divide the file into 2 and give the first part a name
FROM ubuntu:16.04 as builder
RUN apt-get -y update
RUN apt-get -y install curl
RUN curl https://google.com | wc > google-size

# use a small image (alpine) and copy what was done above in the next step to decrease the size of the final image
FROM alpine
COPY --from=builder /google-size /google-size
ENTRYPOINT echo google is this big; cat google-size
